### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by AceroM** [jonfranco224/pixel-art#3]
commands like ctrl + z for undoing, ctrl + c for copying or b to go into brush mode just like how photoshop does it would be a cool feature.

**Comment by jonfranco224** [comment]
I assume this is closed because you found those were in there? I should probably add a keyboard icon somewhere in case people want to know. I was planning on adding a general help menu for a guide on the app basics.

**Comment by AceroM** [comment]
> I assume this is closed because you found those were in there? I should probably add a keyboard icon somewhere in case people want to know. I was planning on adding a general help menu for a guide on the app basics.

yeah basically, sorry about that :(
